server {
    listen 80;
    server_name localhost;

    root /var/www/public_html;
    index index.php index.html index.htm;

   

    location ~ \.php$ {
         try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass php2:9000;  # Используйте имя сервиса из Docker Compose
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        internal;
    }
}

