/**
 * Spanish Trainer — Mezcla (смешанное чтение)
 * 6 текстов, каждый ~60 смысловых токенов {ru, es}
 */

const MEZCLA_DATA = [

  {
    id: 1,
    emoji: "🛒",
    title: "В магазине",
    titleEs: "En la tienda",
    tokens: [
      { ru: "Сегодня утром", es: "Esta mañana" },
      { ru: "я проснулся рано", es: "me desperté pronto" },
      { ru: "и вспомнил,", es: "y recordé" },
      { ru: "что холодильник почти пустой.", es: "que la nevera estaba casi vacía." },
      { ru: "Я написал список покупок", es: "Escribí la lista de la compra" },
      { ru: "и отправился", es: "y me fui" },
      { ru: "в ближайший супермаркет.", es: "al supermercado más cercano." },
      { ru: "На парковке", es: "En el aparcamiento" },
      { ru: "было мало машин,", es: "había pocos coches," },
      { ru: "так как было раннее утро.", es: "ya que era temprano." },
      { ru: "У входа", es: "A la entrada" },
      { ru: "я взял корзину,", es: "cogí una cesta," },
      { ru: "а не тележку —", es: "y no un carrito —" },
      { ru: "много покупать не планировал.", es: "no planeaba comprar mucho." },
      { ru: "Сначала", es: "Primero" },
      { ru: "я направился", es: "me dirigí" },
      { ru: "в молочный отдел.", es: "a la sección de lácteos." },
      { ru: "Там я нашёл", es: "Allí encontré" },
      { ru: "молоко, кефир", es: "leche, kéfir" },
      { ru: "и любимый йогурт.", es: "y el yogur favorito." },
      { ru: "Потом", es: "Luego" },
      { ru: "я перешёл", es: "fui" },
      { ru: "в овощной отдел.", es: "a la sección de verduras." },
      { ru: "Помидоры", es: "Los tomates" },
      { ru: "выглядели свежими и красными.", es: "parecían frescos y rojos." },
      { ru: "Я взял", es: "Cogí" },
      { ru: "кило помидоров", es: "un kilo de tomates" },
      { ru: "и пучок зелёного лука.", es: "y un manojo de cebolleta." },
      { ru: "В хлебном отделе", es: "En la panadería" },
      { ru: "запах был невероятным.", es: "el olor era increíble." },
      { ru: "Я не удержался", es: "No pude resistirme" },
      { ru: "и купил свежую булочку.", es: "y compré un panecillo fresco." },
      { ru: "Кусочек откусил прямо там.", es: "Le di un bocado allí mismo." },
      { ru: "Мясной отдел", es: "La carnicería" },
      { ru: "находился в дальнем конце.", es: "estaba al fondo del pasillo." },
      { ru: "Продавец посоветовал", es: "El carnicero me recomendó" },
      { ru: "взять куриное филе —", es: "tomar pechuga de pollo —" },
      { ru: "сегодня была свежая партия.", es: "hoy había llegado una remesa fresca." },
      { ru: "Я согласился", es: "Acepté" },
      { ru: "и попросил нарезать потоньше.", es: "y pedí que lo cortaran fino." },
      { ru: "Ещё я зашёл", es: "También pasé" },
      { ru: "в отдел напитков", es: "por la sección de bebidas" },
      { ru: "и выбрал", es: "y elegí" },
      { ru: "апельсиновый сок", es: "zumo de naranja" },
      { ru: "и минеральную воду.", es: "y agua mineral." },
      { ru: "На кассе", es: "En la caja" },
      { ru: "была небольшая очередь.", es: "había una pequeña cola." },
      { ru: "Молодой кассир", es: "El cajero joven" },
      { ru: "работал быстро и уверенно.", es: "trabajaba de forma rápida y segura." },
      { ru: "Он спросил:", es: "Me preguntó:" },
      { ru: "«Пакет нужен?»", es: "«¿Necesita bolsa?»" },
      { ru: "Я сказал:", es: "Le dije:" },
      { ru: "«Нет, спасибо,", es: "«No, gracias," },
      { ru: "у меня есть свой».", es: "tengo la mía»." },
      { ru: "Я заплатил картой,", es: "Pagué con tarjeta," },
      { ru: "взял чек", es: "cogí el ticket" },
      { ru: "и вышел из магазина.", es: "y salí del supermercado." },
      { ru: "На свежем воздухе", es: "Al aire libre" },
      { ru: "я почувствовал себя отлично —", es: "me sentí muy bien —" },
      { ru: "всё куплено,", es: "todo comprado," },
      { ru: "планы выполнены.", es: "misión cumplida." }
    ]
  },

  {
    id: 2,
    emoji: "🍽️",
    title: "В ресторане",
    titleEs: "En el restaurante",
    tokens: [
      { ru: "В пятницу вечером", es: "El viernes por la tarde" },
      { ru: "мы с другом", es: "mi amigo y yo" },
      { ru: "решили поужинать вне дома.", es: "decidimos cenar fuera." },
      { ru: "Мы выбрали итальянский ресторан", es: "Elegimos un restaurante italiano" },
      { ru: "в старом районе города.", es: "en el barrio antiguo de la ciudad." },
      { ru: "Снаружи висела уютная вывеска,", es: "Fuera había un cartel acogedor," },
      { ru: "и из окна доносился", es: "y por la ventana llegaba" },
      { ru: "аромат свежей пасты.", es: "el aroma de pasta fresca." },
      { ru: "Нас встретил официант", es: "Nos recibió un camarero" },
      { ru: "в белом фартуке.", es: "con delantal blanco." },
      { ru: "Он проводил нас", es: "Nos llevó" },
      { ru: "к столику у камина.", es: "a una mesa junto a la chimenea." },
      { ru: "Атмосфера была тёплой", es: "La atmósfera era cálida" },
      { ru: "и приятной.", es: "y agradable." },
      { ru: "Официант принёс меню", es: "El camarero trajo la carta" },
      { ru: "и бутылку воды.", es: "y una botella de agua." },
      { ru: "Он порекомендовал", es: "Nos recomendó" },
      { ru: "фирменную пасту карбонара", es: "la pasta carbonara de la casa" },
      { ru: "и ризотто с грибами.", es: "y el risotto con setas." },
      { ru: "Мы долго выбирали", es: "Tardamos mucho en elegir" },
      { ru: "и в итоге", es: "y al final" },
      { ru: "каждый взял своё:", es: "cada uno pidió lo suyo:" },
      { ru: "я — пасту,", es: "yo pedí pasta," },
      { ru: "друг — пиццу Маргарита.", es: "mi amigo pidió pizza Margarita." },
      { ru: "Пока ждали заказ,", es: "Mientras esperábamos el pedido," },
      { ru: "мы разговаривали", es: "hablamos" },
      { ru: "о работе и планах", es: "de trabajo y de planes" },
      { ru: "на выходные.", es: "para el fin de semana." },
      { ru: "Еда пришла быстро.", es: "La comida llegó pronto." },
      { ru: "Паста была восхитительной —", es: "La pasta era exquisita —" },
      { ru: "нежной, ароматной", es: "suave, aromática" },
      { ru: "и в меру солёной.", es: "y con el punto de sal justo." },
      { ru: "Друг тоже остался доволен.", es: "Mi amigo también quedó contento." },
      { ru: "Официант периодически подходил", es: "El camarero se acercaba de vez en cuando" },
      { ru: "и спрашивал,", es: "y preguntaba" },
      { ru: "всё ли хорошо.", es: "si todo estaba bien." },
      { ru: "На десерт", es: "De postre" },
      { ru: "мы взяли тирамису", es: "pedimos tiramisú" },
      { ru: "на двоих.", es: "para los dos." },
      { ru: "Он был нежным,", es: "Estaba suave," },
      { ru: "с лёгкой горчинкой кофе.", es: "con un ligero amargor de café." },
      { ru: "К чаю", es: "Con el té" },
      { ru: "официант принёс", es: "el camarero trajo" },
      { ru: "маленькие шоколадные конфеты.", es: "pequeños bombones de chocolate." },
      { ru: "Мы попросили счёт.", es: "Pedimos la cuenta." },
      { ru: "Цены оказались", es: "Los precios resultaron" },
      { ru: "вполне приятными", es: "bastante razonables" },
      { ru: "для такого уровня заведения.", es: "para un restaurante de ese nivel." },
      { ru: "Мы оставили хорошие чаевые —", es: "Dejamos buena propina —" },
      { ru: "официант этого заслуживал.", es: "el camarero se lo merecía." },
      { ru: "На выходе нас поблагодарили", es: "A la salida nos agradecieron" },
      { ru: "и пригласили снова.", es: "y nos invitaron a volver." },
      { ru: "На улице", es: "En la calle" },
      { ru: "было уже темно, но тепло.", es: "ya era de noche, pero hacía calor." },
      { ru: "Мы медленно пошли", es: "Caminamos despacio" },
      { ru: "к метро", es: "hacia el metro" },
      { ru: "и договорились", es: "y quedamos" },
      { ru: "повторить это", es: "en repetir esto" },
      { ru: "через пару недель.", es: "en un par de semanas." }
    ]
  },

  {
    id: 3,
    emoji: "✈️",
    title: "В аэропорту",
    titleEs: "En el aeropuerto",
    tokens: [
      { ru: "Наш рейс", es: "Nuestro vuelo" },
      { ru: "вылетал рано утром,", es: "salía muy de mañana," },
      { ru: "поэтому мы встали", es: "así que nos levantamos" },
      { ru: "в четыре часа.", es: "a las cuatro." },
      { ru: "Такси заказали заранее —", es: "Habíamos pedido el taxi con antelación —" },
      { ru: "водитель приехал ровно в пять.", es: "el conductor llegó justo a las cinco." },
      { ru: "Дорога до аэропорта", es: "El camino al aeropuerto" },
      { ru: "заняла сорок минут.", es: "tardó cuarenta minutos." },
      { ru: "В аэропорту", es: "En el aeropuerto" },
      { ru: "было много людей", es: "había mucha gente" },
      { ru: "даже в такой ранний час.", es: "incluso a esa hora tan temprana." },
      { ru: "Мы нашли", es: "Encontramos" },
      { ru: "стойку регистрации", es: "el mostrador de facturación" },
      { ru: "нашей авиакомпании.", es: "de nuestra compañía aérea." },
      { ru: "Очередь двигалась медленно.", es: "La cola avanzaba despacio." },
      { ru: "Наконец подошла наша очередь.", es: "Por fin llegó nuestro turno." },
      { ru: "Сотрудница взяла паспорта", es: "La empleada tomó los pasaportes" },
      { ru: "и проверила бронирование.", es: "y comprobó la reserva." },
      { ru: "Мы сдали багаж", es: "Facturamos el equipaje" },
      { ru: "и получили", es: "y recibimos" },
      { ru: "посадочные талоны.", es: "las tarjetas de embarque." },
      { ru: "Нам попались места у окна —", es: "Nos tocaron asientos de ventanilla —" },
      { ru: "просто отлично!", es: "¡genial!" },
      { ru: "Перед паспортным контролем", es: "Antes del control de pasaportes" },
      { ru: "мы зашли в кафе", es: "entramos en una cafetería" },
      { ru: "и взяли по чашке кофе.", es: "y tomamos una taza de café cada uno." },
      { ru: "Это помогло проснуться.", es: "Eso ayudó a despertar." },
      { ru: "На паспортном контроле", es: "En el control de pasaportes" },
      { ru: "очередь была небольшой.", es: "la cola era corta." },
      { ru: "Пограничник", es: "El agente de fronteras" },
      { ru: "просмотрел паспорт", es: "revisó el pasaporte" },
      { ru: "и поставил штамп.", es: "y selló." },
      { ru: "После досмотра безопасности", es: "Después del control de seguridad" },
      { ru: "мы оказались", es: "llegamos" },
      { ru: "в зоне дьюти-фри.", es: "a la zona libre de impuestos." },
      { ru: "Там можно было купить", es: "Allí se podía comprar" },
      { ru: "духи, алкоголь", es: "perfumes, alcohol" },
      { ru: "и шоколад по хорошим ценам.", es: "y chocolate a buen precio." },
      { ru: "Мы поддались соблазну", es: "Nos dejamos llevar" },
      { ru: "и купили пару плиток шоколада.", es: "y compramos un par de tabletas de chocolate." },
      { ru: "Наш гейт G14", es: "Nuestra puerta G14" },
      { ru: "находился в дальнем конце терминала.", es: "estaba al final del terminal." },
      { ru: "Мы шли почти десять минут.", es: "Caminamos casi diez minutos." },
      { ru: "У гейта", es: "En la puerta" },
      { ru: "уже собралось много пассажиров.", es: "ya se había reunido mucha gente." },
      { ru: "По громкой связи", es: "Por megafonía" },
      { ru: "объявили посадку.", es: "anunciaron el embarque." },
      { ru: "Пассажиров с детьми", es: "A los pasajeros con niños" },
      { ru: "пригласили войти первыми.", es: "los invitaron a embarcar primero." },
      { ru: "Потом — остальные.", es: "Luego los demás." },
      { ru: "Мы заняли места,", es: "Ocupamos nuestros asientos," },
      { ru: "пристегнули ремни", es: "nos pusimos los cinturones" },
      { ru: "и расслабились.", es: "y nos relajamos." },
      { ru: "Самолёт поднялся в воздух", es: "El avión despegó" },
      { ru: "точно по расписанию.", es: "justo a la hora prevista." },
      { ru: "Внизу мелькали огни города,", es: "Abajo brillaban las luces de la ciudad," },
      { ru: "а потом — только облака.", es: "y luego solo nubes." },
      { ru: "Отпуск начался.", es: "Las vacaciones comenzaron." }
    ]
  },

  {
    id: 4,
    emoji: "🌳",
    title: "В парке",
    titleEs: "En el parque",
    tokens: [
      { ru: "После долгой рабочей недели", es: "Después de una larga semana de trabajo" },
      { ru: "воскресенье", es: "el domingo" },
      { ru: "оказалось настоящим подарком.", es: "resultó ser un regalo." },
      { ru: "Погода была идеальной:", es: "El tiempo era perfecto:" },
      { ru: "ярко светило солнце,", es: "el sol brillaba con fuerza," },
      { ru: "лёгкий ветерок", es: "una ligera brisa" },
      { ru: "освежал воздух.", es: "refrescaba el ambiente." },
      { ru: "Я позвал", es: "Llamé" },
      { ru: "своего старого друга,", es: "a mi viejo amigo," },
      { ru: "и мы решили", es: "y decidimos" },
      { ru: "провести день", es: "pasar el día" },
      { ru: "в большом городском парке.", es: "en el gran parque de la ciudad." },
      { ru: "До парка добрались на велосипеде —", es: "Al parque llegamos en bicicleta —" },
      { ru: "это заняло минут двадцать.", es: "tardamos unos veinte minutos." },
      { ru: "У входа продавали мороженое,", es: "A la entrada vendían helado," },
      { ru: "и мы не устояли.", es: "y no pudimos resistirnos." },
      { ru: "В парке было оживлённо:", es: "En el parque había animación:" },
      { ru: "одни люди бегали,", es: "unas personas corrían," },
      { ru: "другие катались на роликах,", es: "otras patinaban," },
      { ru: "третьи просто гуляли", es: "otras simplemente paseaban" },
      { ru: "с детьми и собаками.", es: "con niños y perros." },
      { ru: "Мы нашли", es: "Encontramos" },
      { ru: "свободную скамейку", es: "un banco libre" },
      { ru: "возле фонтана.", es: "cerca de la fuente." },
      { ru: "Фонтан работал,", es: "La fuente funcionaba," },
      { ru: "вода блестела на солнце.", es: "el agua brillaba al sol." },
      { ru: "Мы посидели,", es: "Nos sentamos," },
      { ru: "поговорили о жизни,", es: "hablamos de la vida," },
      { ru: "вспомнили старые времена.", es: "recordamos viejos tiempos." },
      { ru: "Потом решили", es: "Luego decidimos" },
      { ru: "обойти весь парк", es: "dar una vuelta por todo el parque" },
      { ru: "по кольцевой дорожке.", es: "por el camino circular." },
      { ru: "Дорожка шла", es: "El camino pasaba" },
      { ru: "через небольшой лес,", es: "por un pequeño bosque," },
      { ru: "мимо пруда", es: "junto al estanque" },
      { ru: "и детской площадки.", es: "y el parque infantil." },
      { ru: "На пруду плавали белые лебеди.", es: "En el estanque nadaban cisnes blancos." },
      { ru: "Мой друг остановился", es: "Mi amigo se detuvo" },
      { ru: "и сфотографировал их.", es: "y los fotografió." },
      { ru: "Мы купили", es: "Compramos" },
      { ru: "у лотка с едой", es: "en un puesto de comida" },
      { ru: "хот-доги и лимонад.", es: "perritos calientes y limonada." },
      { ru: "Устроились на траве", es: "Nos instalamos en el césped" },
      { ru: "и пообедали под деревьями.", es: "y comimos bajo los árboles." },
      { ru: "После обеда", es: "Después de comer" },
      { ru: "мы поиграли в бадминтон.", es: "jugamos al bádminton." },
      { ru: "Друг выиграл три раза,", es: "Mi amigo ganó tres veces," },
      { ru: "я — два.", es: "yo dos." },
      { ru: "К вечеру", es: "Al atardecer" },
      { ru: "парк начал пустеть.", es: "el parque empezó a vaciarse." },
      { ru: "Небо покрылось", es: "El cielo se llenó" },
      { ru: "розовыми и оранжевыми тонами.", es: "de tonos rosas y naranjas." },
      { ru: "Мы сели на велосипеды", es: "Subimos a las bicicletas" },
      { ru: "и поехали домой.", es: "y nos fuimos a casa." },
      { ru: "По дороге", es: "Por el camino" },
      { ru: "почти не разговаривали —", es: "casi no hablamos —" },
      { ru: "просто наслаждались", es: "simplemente disfrutamos" },
      { ru: "тихим вечером.", es: "de la tarde tranquila." }
    ]
  },

  {
    id: 5,
    emoji: "🤝",
    title: "Знакомство",
    titleEs: "El encuentro",
    tokens: [
      { ru: "Три месяца назад", es: "Hace tres meses" },
      { ru: "я начал ходить", es: "empecé a asistir" },
      { ru: "на курсы испанского.", es: "a las clases de español." },
      { ru: "Учитель был молодым", es: "El profesor era joven" },
      { ru: "и очень энергичным.", es: "y muy enérgico." },
      { ru: "Занятия проходили", es: "Las clases tenían lugar" },
      { ru: "по вторникам и четвергам.", es: "los martes y los jueves." },
      { ru: "В группе нас было", es: "En el grupo éramos" },
      { ru: "восемь человек.", es: "ocho personas." },
      { ru: "Однажды", es: "Un día" },
      { ru: "рядом со мной", es: "a mi lado" },
      { ru: "сел новый студент", es: "se sentó un estudiante nuevo" },
      { ru: "по имени Пабло.", es: "llamado Pablo." },
      { ru: "Он был из Барселоны,", es: "Era de Barcelona," },
      { ru: "но уже три года", es: "pero llevaba ya tres años" },
      { ru: "жил в нашем городе.", es: "viviendo en nuestra ciudad." },
      { ru: "Он представился", es: "Se presentó" },
      { ru: "с лёгким испанским акцентом,", es: "con un ligero acento español," },
      { ru: "и все сразу улыбнулись.", es: "y todos sonrieron al instante." },
      { ru: "После занятий", es: "Después de la clase" },
      { ru: "несколько человек", es: "varios de nosotros" },
      { ru: "пошли в кафе", es: "fuimos a una cafetería" },
      { ru: "неподалёку.", es: "cercana." },
      { ru: "Пабло пришёл с нами.", es: "Pablo vino con nosotros." },
      { ru: "Мы заказали кофе и пирожки.", es: "Pedimos café y pasteles." },
      { ru: "Пабло рассказал,", es: "Pablo nos contó" },
      { ru: "что работает дизайнером,", es: "que trabaja como diseñador," },
      { ru: "любит горы", es: "le gustan las montañas" },
      { ru: "и увлекается серфингом.", es: "y le apasiona el surf." },
      { ru: "Мы спросили,", es: "Le preguntamos" },
      { ru: "скучает ли он по Испании.", es: "si echaba de menos España." },
      { ru: "Он засмеялся и сказал,", es: "Se rió y dijo" },
      { ru: "что скучает по еде —", es: "que echaba de menos la comida —" },
      { ru: "особенно по тапас", es: "sobre todo las tapas" },
      { ru: "и паэлье.", es: "y la paella." },
      { ru: "Я рассказал,", es: "Yo conté" },
      { ru: "что изучаю испанский", es: "que estudio español" },
      { ru: "уже полгода", es: "desde hace medio año" },
      { ru: "и мечтаю поехать", es: "y sueño con ir" },
      { ru: "в Мадрид летом.", es: "a Madrid en verano." },
      { ru: "Пабло обрадовался", es: "Pablo se alegró" },
      { ru: "и сразу же предложил", es: "y al momento se ofreció" },
      { ru: "показать нам лучшие места столицы.", es: "a enseñarnos los mejores lugares de la capital." },
      { ru: "Мы обменялись номерами", es: "Nos intercambiamos los números" },
      { ru: "и договорились снова встретиться.", es: "y quedamos en volver a quedar." },
      { ru: "С тех пор", es: "Desde entonces" },
      { ru: "мы видимся каждую неделю.", es: "nos vemos cada semana." },
      { ru: "Пабло помогает мне", es: "Pablo me ayuda" },
      { ru: "с произношением,", es: "con la pronunciación," },
      { ru: "а я учу его", es: "y yo le enseño" },
      { ru: "русским фразам.", es: "frases en ruso." },
      { ru: "Такой обмен", es: "Este intercambio" },
      { ru: "оказался очень полезным", es: "resultó muy útil" },
      { ru: "для нас обоих.", es: "para los dos." },
      { ru: "Думаю, что Пабло —", es: "Creo que Pablo es" },
      { ru: "один из лучших друзей,", es: "uno de los mejores amigos" },
      { ru: "которых я когда-либо встречал.", es: "que he conocido nunca." }
    ]
  },

  {
    id: 6,
    emoji: "🌦️",
    title: "Погода и природа",
    titleEs: "El tiempo y la naturaleza",
    tokens: [
      { ru: "Осень в нашем городе", es: "El otoño en nuestra ciudad" },
      { ru: "наступает внезапно:", es: "llega de repente:" },
      { ru: "ещё вчера", es: "ayer todavía" },
      { ru: "было тепло и солнечно,", es: "hacía calor y sol," },
      { ru: "а сегодня", es: "pero hoy" },
      { ru: "уже моросит дождь", es: "ya llovizna" },
      { ru: "и дует холодный ветер.", es: "y sopla viento frío." },
      { ru: "Деревья в парке", es: "Los árboles del parque" },
      { ru: "меняют цвет:", es: "cambian de color:" },
      { ru: "листья становятся", es: "las hojas se vuelven" },
      { ru: "жёлтыми, рыжими, красными.", es: "amarillas, anaranjadas, rojas." },
      { ru: "Это красиво,", es: "Es bonito," },
      { ru: "но немного грустно.", es: "pero un poco triste." },
      { ru: "По утрам на траве", es: "Por las mañanas sobre la hierba" },
      { ru: "лежит густой туман —", es: "hay niebla densa —" },
      { ru: "белый и тихий.", es: "blanca y silenciosa." },
      { ru: "Солнце появляется", es: "El sol aparece" },
      { ru: "только к полудню,", es: "solo al mediodía," },
      { ru: "но уже не греет", es: "pero ya no calienta" },
      { ru: "так сильно, как летом.", es: "tan fuerte como en verano." },
      { ru: "Температура", es: "La temperatura" },
      { ru: "опустилась до десяти градусов.", es: "bajó hasta los diez grados." },
      { ru: "Люди достали", es: "La gente sacó" },
      { ru: "куртки и плащи", es: "chaquetas e impermeables" },
      { ru: "из дальних шкафов.", es: "del fondo de los armarios." },
      { ru: "На улицах стало меньше велосипедистов", es: "En las calles hay menos ciclistas" },
      { ru: "и больше зонтиков.", es: "y más paraguas." },
      { ru: "В один из таких дней", es: "En uno de esos días" },
      { ru: "я вышел", es: "salí" },
      { ru: "на утреннюю прогулку.", es: "a dar un paseo matutino." },
      { ru: "Воздух был", es: "El aire estaba" },
      { ru: "свежим и влажным.", es: "fresco y húmedo." },
      { ru: "Пахло", es: "Olía" },
      { ru: "мокрой листвой", es: "a hojas mojadas" },
      { ru: "и землёй.", es: "y a tierra." },
      { ru: "Я шёл", es: "Caminé" },
      { ru: "по набережной", es: "por el paseo marítimo" },
      { ru: "вдоль реки.", es: "a lo largo del río." },
      { ru: "Вода в реке", es: "El agua del río" },
      { ru: "стала тёмной", es: "se había vuelto oscura" },
      { ru: "и неспокойной.", es: "e inquieta." },
      { ru: "Несколько уток", es: "Unos patos" },
      { ru: "плыли по течению.", es: "nadaban con la corriente." },
      { ru: "На скамейке", es: "En el banco" },
      { ru: "сидела пожилая женщина", es: "estaba sentada una señora mayor" },
      { ru: "с книгой.", es: "con un libro." },
      { ru: "Несмотря на холод", es: "A pesar del frío" },
      { ru: "и серое небо,", es: "y el cielo gris," },
      { ru: "на её лице было спокойствие.", es: "en su rostro había tranquilidad." },
      { ru: "Дойдя до конца набережной,", es: "Al llegar al final del paseo," },
      { ru: "я развернулся", es: "di la vuelta" },
      { ru: "и пошёл обратно.", es: "y volví." },
      { ru: "Дома", es: "En casa" },
      { ru: "меня ждала", es: "me esperaba" },
      { ru: "горячая чашка чая", es: "una taza de té caliente" },
      { ru: "и любимый плед.", es: "y la manta favorita." },
      { ru: "Осень — это тоже хорошо,", es: "El otoño también tiene lo suyo," },
      { ru: "если знаешь, как её принять.", es: "si sabes cómo aceptarlo." }
    ]
  }

];
