/* subjuntivo/data.js v=1 — 12 тем, 5 вопросов каждая */

var SUBJUNTIVO_DATA = [

  /* ── 1. Глаголы -AR ── */
  {
    id: 0, name: 'Глаголы -AR', tag: 'Морфология',
    rule: 'Глаголы на -AR получают «противоположные» гласные:\n-e, -es, -e, -emos, -éis, -en\n\nОснова = Infinitivo без -AR.\nОрфография: llegar → llegue (g→gu перед e), buscar → busque (c→qu).',
    examples: [
      'hablar → hable, hables, hable, hablemos, habléis, hablen',
      'trabajar → trabaje, trabajes, trabaje...',
      'llegar → llegue, llegues, llegue... (g→gu)',
    ],
    questions: [
      { type: 'fill', sentence: 'Es posible que Ana ___ mañana.', sentenceRu: 'Возможно, Ана придёт завтра.', verb: 'llegar (ella)',
        tiles: ['llegue', 'llega', 'llegó', 'llegar'], correct: 0,
        hint: 'es posible que → Subjuntivo\nllegar + ella → llegue (g→gu перед e)' },
      { type: 'fill', sentence: 'Quiero que tú ___ conmigo.', sentenceRu: 'Я хочу, чтобы ты говорил со мной.', verb: 'hablar (tú)',
        tiles: ['hables', 'hablas', 'hablaste', 'hablarás'], correct: 0,
        hint: 'querer que → Subjuntivo (два субъекта)\nhablar + tú → hables' },
      { question: '¿Cuál es la forma de Subjuntivo?  «Espero que ella ___ el proyecto.»  (terminar)',
        options: ['termine', 'termina', 'terminó', 'terminará'], correct: 0,
        hint: 'esperar que → Subjuntivo\nterminar + ella → termine (-AR → -e)' },
      { question: 'Es mejor que nosotros ___ más.  (estudiar)',
        options: ['estudiemos', 'estudiamos', 'estudiábamos', 'estudiaremos'], correct: 0,
        hint: 'es mejor que → Subjuntivo\nestudiar + nosotros → estudiemos (-AR → -emos)' },
      { type: 'fill', sentence: 'No me parece bien que vosotros ___ tarde.', sentenceRu: 'Мне не нравится, что вы опаздываете.', verb: 'llegar (vosotros)',
        tiles: ['lleguéis', 'llegáis', 'llegasteis', 'llegaréis'], correct: 0,
        hint: 'no parecer bien que → Subjuntivo\nllegar + vosotros → lleguéis (g→gu)' },
    ],
  },

  /* ── 2. Глаголы -ER/-IR ── */
  {
    id: 1, name: 'Глаголы -ER и -IR', tag: 'Морфология',
    rule: 'Глаголы на -ER/-IR получают «противоположные» гласные:\n-a, -as, -a, -amos, -áis, -an\n\nОснова = Infinitivo без -ER/-IR.',
    examples: [
      'comer → coma, comas, coma, comamos, comáis, coman',
      'vivir → viva, vivas, viva, vivamos, viváis, vivan',
      'escribir → escriba, escribas, escriba...',
    ],
    questions: [
      { type: 'fill', sentence: 'Es importante que tú ___ bien.', sentenceRu: 'Важно, чтобы ты хорошо питался.', verb: 'comer (tú)',
        tiles: ['comas', 'comes', 'comiste', 'comerás'], correct: 0,
        hint: 'es importante que → Subjuntivo\ncomer + tú → comas (-ER → -as)' },
      { question: 'Quiero que mis hijos ___ en España.  (vivir)',
        options: ['vivan', 'viven', 'vivieron', 'vivirán'], correct: 0,
        hint: 'querer que → Subjuntivo (два субъекта)\nvivir + ellos → vivan (-IR → -an)' },
      { type: 'fill', sentence: 'Es posible que yo ___ una carta mañana.', sentenceRu: 'Возможно, я напишу письмо завтра.', verb: 'escribir (yo)',
        tiles: ['escriba', 'escribo', 'escribí', 'escribiré'], correct: 0,
        hint: 'es posible que → Subjuntivo\nescribir + yo → escriba (-IR → -a)' },
      { question: 'Espero que vosotros ___ la situación.  (comprender)',
        options: ['comprendáis', 'comprendéis', 'comprendisteis', 'comprenderéis'], correct: 0,
        hint: 'esperar que → Subjuntivo\ncomprender + vosotros → comprendáis (-ER → -áis)' },
      { question: 'Es malo que los niños no ___ cada día.  (correr)',
        options: ['corran', 'corren', 'corrieron', 'correrán'], correct: 0,
        hint: 'es malo que → Subjuntivo\ncorrer + ellos → corran (-ER → -an)' },
    ],
  },

  /* ── 3. Неправильные (основа yo-формы) ── */
  {
    id: 2, name: 'Неправильные: основа yo', tag: 'Морфология',
    rule: 'Если yo-форма в Indicativo неправильная — эта же основа используется во всех лицах Subjuntivo.\n\ndigo → diga, digas, diga, digamos, digáis, digan\nhago → haga  |  tengo → tenga  |  pongo → ponga\nconozco → conozca  |  salgo → salga  |  vengo → venga\npierdo → pierda (E→IE стейм-чейндж)',
    examples: [
      'decir: yo digo → dig- → diga, digas, diga...',
      'hacer: yo hago → hag- → haga, hagas, haga...',
      'tener: yo tengo → teng- → tenga, tengas...',
    ],
    questions: [
      { type: 'fill', sentence: 'Te pido que me ___ la verdad.', sentenceRu: 'Я прошу тебя сказать мне правду.', verb: 'decir (tú)',
        tiles: ['digas', 'dices', 'dijiste', 'dirás'], correct: 0,
        hint: 'pedir que → Subjuntivo\ndecir: yo digo → dig- → tú digas' },
      { question: 'Es posible que Pablo ___ la comida.  (hacer)',
        options: ['haga', 'hace', 'hizo', 'hará'], correct: 0,
        hint: 'es posible que → Subjuntivo\nhacer: yo hago → hag- → él haga' },
      { type: 'fill', sentence: 'Necesito que tú ___ paciencia.', sentenceRu: 'Мне нужно, чтобы у тебя было терпение.', verb: 'tener (tú)',
        tiles: ['tengas', 'tienes', 'tuviste', 'tendrás'], correct: 0,
        hint: 'necesitar que → Subjuntivo\ntener: yo tengo → teng- → tú tengas' },
      { question: 'Quiero que ella ___ a mis amigos.  (conocer)',
        options: ['conozca', 'conoce', 'conoció', 'conocerá'], correct: 0,
        hint: 'querer que → Subjuntivo\nconocer: yo conozco → conozc- → ella conozca' },
      { type: 'fill', sentence: 'Es importante que vosotros ___ temprano.', sentenceRu: 'Важно, чтобы вы вышли пораньше.', verb: 'salir (vosotros)',
        tiles: ['salgáis', 'salís', 'salisteis', 'saldréis'], correct: 0,
        hint: 'es importante que → Subjuntivo\nsalir: yo salgo → salg- → vosotros salgáis' },
    ],
  },

  /* ── 4. Ser / ir / saber / haber ── */
  {
    id: 3, name: 'Ser, ir, saber, haber', tag: 'Морфология',
    rule: 'Четыре глагола с особыми формами Subjuntivo:\n\nser  → sea, seas, sea, seamos, seáis, sean\nir   → vaya, vayas, vaya, vayamos, vayáis, vayan\nsaber → sepa, sepas, sepa, sepamos, sepáis, sepan\nhaber → haya (вспомогательный)',
    examples: [
      'Es bueno que seas amable.',
      'Quiero que vayas al médico.',
      'No creo que sepa la respuesta.',
      'Espero que haya buenas noticias.',
    ],
    questions: [
      { type: 'fill', sentence: 'Es importante que tú ___ puntual.', sentenceRu: 'Важно, чтобы ты был пунктуальным.', verb: 'ser (tú)',
        tiles: ['seas', 'eres', 'fuiste', 'serás'], correct: 0,
        hint: 'es importante que → Subjuntivo\nser (irregulare) → tú seas' },
      { question: 'Quiero que mis padres ___ de vacaciones.  (ir)',
        options: ['vayan', 'van', 'fueron', 'irán'], correct: 0,
        hint: 'querer que → Subjuntivo\nir (irregulare) → ellos vayan' },
      { type: 'fill', sentence: 'No creo que Pedro ___ la respuesta.', sentenceRu: 'Я не думаю, что Педро знает ответ.', verb: 'saber (él)',
        tiles: ['sepa', 'sabe', 'supo', 'sabrá'], correct: 0,
        hint: 'No creo que → Subjuntivo (отрицание мнения)\nsaber (irregulare) → él sepa' },
      { question: 'Espero que ___ buenas noticias mañana.  (haber)',
        options: ['haya', 'hay', 'hubo', 'habrá'], correct: 0,
        hint: 'esperar que → Subjuntivo\nhaber → haya' },
      { question: '¡Que todo ___ bien!  (ir)',
        options: ['vaya', 'va', 'fue', 'irá'], correct: 0,
        hint: '¡Que + Subjuntivo! — прямое пожелание\nir → vaya' },
    ],
  },

  /* ── 5. Es + adjetivo + que ── */
  {
    id: 4, name: 'Es + adjetivo + que', tag: 'Конструкции',
    rule: 'После безличных оценочных конструкций → Subjuntivo:\n\nes posible que  |  es bueno/malo que  |  es mejor/peor que\nes increíble que  |  es importante que\n\n⚠ ИСКЛЮЧЕНИЕ — факты требуют Indicativo:\nes verdad que...  |  es seguro que...  |  es obvio que...',
    examples: [
      'Es posible que venga mañana. (оценка → Subj)',
      'Es verdad que viene mañana. (факт → Ind!)',
      'Es increíble que tenga 50 años.',
    ],
    questions: [
      { question: 'Es posible que el tren ___ tarde.  (llegar)',
        options: ['llegue', 'llega', 'llegó', 'llegar'], correct: 0,
        hint: 'es posible que → Subjuntivo (вероятность)\nllegar + él → llegue' },
      { question: 'Es verdad que María ___ muy inteligente.  (ser)',
        options: ['es', 'sea', 'fue', 'será'], correct: 0,
        hint: '«Es verdad que» = факт → Indicativo!\nes verdad que María es... (она действительно такая)' },
      { type: 'fill', sentence: 'Es increíble que tu abuelo ___ solo 60 años.', sentenceRu: 'Невероятно, что твоему дедушке всего 60 лет.', verb: 'tener (él)',
        tiles: ['tenga', 'tiene', 'tuvo', 'tendrá'], correct: 0,
        hint: 'es increíble que → Subjuntivo\ntener: yo tengo → teng- → él tenga' },
      { question: 'Es mejor que vosotros ___ la verdad.  (decir)',
        options: ['digáis', 'decís', 'dijisteis', 'diréis'], correct: 0,
        hint: 'es mejor que → Subjuntivo\ndecir: yo digo → dig- → vosotros digáis' },
      { question: 'Es seguro que Juan ___ mañana.  (venir)',
        options: ['viene', 'venga', 'vino', 'vendrá'], correct: 0,
        hint: '«Es seguro que» = уверенность/факт → Indicativo!\nТолько оценки и вероятность → Subjuntivo.' },
    ],
  },

  /* ── 6. Querer / pedir que — смена субъекта ── */
  {
    id: 5, name: 'Querer/pedir que — два субъекта', tag: 'Конструкции',
    rule: 'Правило двух субъектов:\n\n1 субъект → Infinitivo:\n  Quiero ir al cine. (я сам хочу идти)\n\n2 субъекта → que + Subjuntivo:\n  Quiero que tú vayas conmigo. (ты должен идти)\n\nГлаголы: querer, pedir, necesitar, desear, esperar, exigir, recomendar...',
    examples: [
      'Mi madre quiere trabajar. (сама → Inf)',
      'Mi madre quiere que yo trabaje más. (2 субъекта → Subj)',
      'Te pido que me ayudes.',
    ],
    questions: [
      { question: 'Quiero ___ al gimnasio esta tarde. (yo mismo)',
        options: ['ir', 'vaya', 'voy', 'fui'], correct: 0,
        hint: '1 субъект (я сам хочу идти) → Infinitivo\nQuiero ir... (не: que vaya)' },
      { question: 'Quiero que tú ___ al gimnasio conmigo.',
        options: ['vayas', 'vas', 'fuiste', 'irás'], correct: 0,
        hint: '2 субъекта → que + Subjuntivo\nir + tú → vayas' },
      { type: 'fill', sentence: 'Te pido que me ___ con la mudanza.', sentenceRu: 'Я прошу тебя помочь мне с переездом.', verb: 'ayudar (tú)',
        tiles: ['ayudes', 'ayudas', 'ayudaste', 'ayudarás'], correct: 0,
        hint: 'pedir que → Subjuntivo (2 субъекта)\nayudar + tú → ayudes' },
      { type: 'fill', sentence: 'Mis padres desean que nosotros ___ felices.', sentenceRu: 'Мои родители желают, чтобы мы были счастливы.', verb: 'ser (nosotros)',
        tiles: ['seamos', 'somos', 'fuimos', 'seremos'], correct: 0,
        hint: 'desear que → Subjuntivo\nser → nosotros seamos' },
      { question: 'Necesito ___ temprano hoy. (yo mismo)',
        options: ['levantarme', 'me levante', 'me levanto', 'me levanté'], correct: 0,
        hint: '1 субъект → Infinitivo\nNecesito levantarme. (не: que me levante)' },
    ],
  },

  /* ── 7. ¡Que + Subjuntivo! ── */
  {
    id: 6, name: '¡Que + Subjuntivo! — пожелания', tag: 'Конструкции',
    rule: 'Прямые пожелания без главного глагола — Subjuntivo с начальным «que»:\n\n¡Que tengas suerte! — Удачи!\n¡Que aproveche! — Приятного аппетита!\n¡Que te mejores! — Выздоравливай!\n¡Que descanses! — Отдыхай!\n¡Que vaya bien! — Пусть всё пройдёт хорошо!',
    examples: [
      '¡Que tengas un buen día!',
      '¡Que os divirtáis en la fiesta!',
      '¡Que sea leve! (лёгкой работы)',
    ],
    questions: [
      { question: 'Твой друг идёт на экзамен. Ты желаешь ему:',
        options: ['¡Que tengas suerte!', '¡Que tienes suerte!', '¡Que tuviste suerte!', '¡Tener suerte!'], correct: 0,
        hint: '¡Que + Subjuntivo! — пожелание\ntener + tú → tengas' },
      { question: 'Друг садится за стол. Ты говоришь:',
        options: ['¡Que aproveche!', '¡Que aprovecha!', '¡Que aprovechó!', '¡Aprovechar!'], correct: 0,
        hint: '¡Que aproveche! — устойчивое пожелание (Приятного аппетита)\naprovechar + él → aproveche' },
      { type: 'fill', sentence: '¡Que ___ bien el viaje!', sentenceRu: 'Пусть поездка пройдёт хорошо!', verb: 'ir (ello)',
        tiles: ['vaya', 'va', 'fue', 'irá'], correct: 0,
        hint: '¡Que + Subjuntivo!\nir → vaya' },
      { question: 'Коллега болен. Ты пишешь ему:',
        options: ['¡Que te mejores!', '¡Que te mejoras!', '¡Que te mejorarás!', '¡Mejorar!'], correct: 0,
        hint: '¡Que te mejores! — «Выздоравливай!»\nmejorar(se) + tú → te mejores' },
      { type: 'fill', sentence: '¡Que ___ mucho en la fiesta!', sentenceRu: 'Веселитесь на вечеринке!', verb: 'divertirse (vosotros)',
        tiles: ['os divirtáis', 'os divertís', 'os divertiréis', 'os divertíais'], correct: 0,
        hint: '¡Que + Subjuntivo!\ndivertirse: e→i в nos/vos → os divirtáis' },
    ],
  },

  /* ── 8. Эмоции ── */
  {
    id: 7, name: 'Эмоции: me gusta que...', tag: 'Конструкции',
    rule: 'Verbo de emoción + que + Subjuntivo (при смене субъекта):\n\nme gusta que  |  me alegra que  |  estoy feliz de que\nme molesta que  |  me sorprende que  |  tengo miedo de que\n\n1 субъект → Infinitivo:\n  Me gusta bailar. (я сам)\n  Me gusta que tú bailes. (ты → Subj)',
    examples: [
      'Me gusta que tú hagas deporte.',
      'Estoy feliz de que estudies tanto.',
      'Me molesta que llegues tarde.',
    ],
    questions: [
      { question: 'Me gusta que tú ___ conmigo.  (hablar)',
        options: ['hables', 'hablas', 'hablaste', 'hablarás'], correct: 0,
        hint: 'me gusta que + tú → Subjuntivo\nhablar + tú → hables' },
      { type: 'fill', sentence: 'Estoy feliz de que vosotros ___ aquí.', sentenceRu: 'Я рад, что вы здесь.', verb: 'estar (vosotros)',
        tiles: ['estéis', 'estáis', 'estuvisteis', 'estaréis'], correct: 0,
        hint: 'feliz de que → Subjuntivo\nestar → estéis (с ударением: estéis)' },
      { question: 'Me molesta que los vecinos ___ tanto ruido.  (hacer)',
        options: ['hagan', 'hacen', 'hicieron', 'harán'], correct: 0,
        hint: 'me molestar que → Subjuntivo\nhacer: yo hago → hag- → ellos hagan' },
      { question: 'Me gusta ___ los domingos. (yo сам, pasear)',
        options: ['pasear', 'pasee', 'paseo', 'paseé'], correct: 0,
        hint: '1 субъект → Infinitivo\nMe gusta pasear. (не: que pasee)' },
      { type: 'fill', sentence: 'Me sorprende que ella no ___ la noticia.', sentenceRu: 'Меня удивляет, что она не знает эту новость.', verb: 'saber (ella)',
        tiles: ['sepa', 'sabe', 'supo', 'sabrá'], correct: 0,
        hint: 'me sorprender que → Subjuntivo\nsaber → ella sepa' },
    ],
  },

  /* ── 9. No creo que ── */
  {
    id: 8, name: 'No creo que — отрицание мнения', tag: 'Конструкции',
    rule: 'При ОТРИЦАНИИ глаголов мнения → Subjuntivo:\n\nNo creo que...  |  No pienso que...\nNo me parece bien que...  |  No estoy seguro/a de que...\n\nПри УТВЕРЖДЕНИИ → Indicativo:\n  Creo que llueve. (моё мнение как факт)\n  No creo que llueva. (субъективное отрицание → Subj)',
    examples: [
      'Creo que Juan tiene razón. (Ind)',
      'No creo que Juan tenga razón. (Subj)',
      '¿Piensas que lloverá? — No, no pienso que llueva.',
    ],
    questions: [
      { question: 'Creo que Carlos ___ en casa ahora.  (estar)',
        options: ['está', 'esté', 'estuvo', 'estará'], correct: 0,
        hint: 'Creo que → УТВЕРЖДЕНИЕ → Indicativo\nestar + él → está' },
      { question: 'No creo que Carlos ___ en casa ahora.  (estar)',
        options: ['esté', 'está', 'estuvo', 'estará'], correct: 0,
        hint: 'No creo que → ОТРИЦАНИЕ мнения → Subjuntivo\nestar → él esté' },
      { type: 'fill', sentence: 'No pienso que esto ___ correcto.', sentenceRu: 'Я не думаю, что это правильно.', verb: 'ser (ello)',
        tiles: ['sea', 'es', 'fue', 'será'], correct: 0,
        hint: 'No pensar que → Subjuntivo\nser → sea' },
      { question: 'No me parece bien que vosotros ___ tan tarde.  (llegar)',
        options: ['lleguéis', 'llegáis', 'llegasteis', 'llegaréis'], correct: 0,
        hint: 'no parecer bien que → Subjuntivo\nllegar + vosotros → lleguéis' },
      { type: 'fill', sentence: 'No estoy segura de que mi marido ___ a tiempo.', sentenceRu: 'Я не уверена, что мой муж придёт вовремя.', verb: 'llegar (él)',
        tiles: ['llegue', 'llega', 'llegó', 'llegará'], correct: 0,
        hint: 'No estar segura de que → Subjuntivo\nllegar + él → llegue' },
    ],
  },

  /* ── 10. Cuando: будущее vs привычка ── */
  {
    id: 9, name: 'Cuando + будущее vs привычка', tag: 'Конструкции',
    rule: 'Cuando + Subjuntivo → будущее/неопределённое действие:\n  Cuando llegues a casa, llámame.\n\nCuando + Indicativo → привычка/регулярное:\n  Cuando llego a casa, siempre como.\n\nКлюч: есть маркер будущего (mañana, el próximo año...) или ситуация впервые/неопределённо → Subjuntivo',
    examples: [
      'Cuando vaya a la playa, me bañaré. (Subj — будущее)',
      'Cuando voy a la playa, siempre me baño. (Ind — привычка)',
      'Cuando vea a tu madre, le preguntaré. (Subj)',
    ],
    questions: [
      { question: 'Cuando ___ a casa mañana, te llamaré.  (llegar, tú)',
        options: ['llegues', 'llegas', 'llegaste', 'llegarás'], correct: 0,
        hint: '«mañana» = будущее → cuando + Subjuntivo\nllegar + tú → llegues' },
      { question: 'Cuando ___ a casa, siempre me ducho.  (llegar, yo — привычка)',
        options: ['llego', 'llegue', 'llegué', 'llegaré'], correct: 0,
        hint: '«siempre» = привычка → cuando + Indicativo\nllego (presente de indicativo)' },
      { type: 'fill', sentence: 'Cuando ___ mayor, quiero ser médico.', sentenceRu: 'Когда вырасту, хочу стать врачом.', verb: 'ser (yo) — futuro implícito',
        tiles: ['sea', 'soy', 'fui', 'seré'], correct: 0,
        hint: 'Будущее имплицитное → cuando + Subjuntivo\nser → yo sea' },
      { question: 'Cuando tengo tiempo, ___ libros.  (leer — привычка)',
        options: ['leo', 'lea', 'leí', 'leeré'], correct: 0,
        hint: 'Регулярная привычка → Indicativo\nleer + yo → leo' },
      { type: 'fill', sentence: 'Cuando ___ a tu padre, le daré el mensaje.', sentenceRu: 'Когда увижу твоего отца, передам ему сообщение.', verb: 'ver (yo) — futuro',
        tiles: ['vea', 'veo', 'vi', 'veré'], correct: 0,
        hint: 'Будущее → cuando + Subjuntivo\nver: yo veo → ve- → yo vea' },
    ],
  },

  /* ── 11. para que / aunque / ojalá ── */
  {
    id: 10, name: 'Para que, aunque, ojalá', tag: 'Союзы',
    rule: 'Три союза, всегда требующие Subjuntivo:\n\npara que + Subj (цель):\n  Te llamo para que sepas la noticia.\n\naunque + Subj (гипотеза/будущее):\n  Aunque haga frío, iremos a la playa.\n\nojalá (que) + Subj (надежда/желание):\n  ¡Ojalá que puedas venir!',
    examples: [
      'Para que mi madre esté tranquila, la llamo cada día.',
      'Aunque no tenga dinero, iré al concierto.',
      '¡Ojalá que todo salga bien!',
    ],
    questions: [
      { question: 'Te explico esto para que lo ___.  (entender)',
        options: ['entiendas', 'entiendes', 'entendiste', 'entenderás'], correct: 0,
        hint: 'para que → всегда Subjuntivo (цель)\nentender (E→IE): entiendo → entiend- → tú entiendas' },
      { type: 'fill', sentence: '¡Ojalá que tus padres ___ venir a la fiesta!', sentenceRu: 'Вот если бы твои родители смогли прийти!', verb: 'poder (ellos)',
        tiles: ['puedan', 'pueden', 'pudieron', 'podrán'], correct: 0,
        hint: 'ojalá que → Subjuntivo\npoder (E→UE): puedo → pued- → ellos puedan' },
      { question: 'Aunque ___ frío mañana, saldremos a correr.  (hacer)',
        options: ['haga', 'hace', 'hizo', 'hará'], correct: 0,
        hint: 'aunque + гипотеза/будущее → Subjuntivo\nhacer: yo hago → hag- → haga' },
      { type: 'fill', sentence: 'Te dejo mi número para que me ___ cuando llegues.', sentenceRu: 'Оставлю тебе номер, чтобы ты позвонил, когда приедешь.', verb: 'llamar (tú)',
        tiles: ['llames', 'llamas', 'llamaste', 'llamarás'], correct: 0,
        hint: 'para que → Subjuntivo\nllamar + tú → llames' },
      { question: '¡Ojalá que ___ buen tiempo este fin de semana!  (hacer)',
        options: ['haga', 'hace', 'hizo', 'hará'], correct: 0,
        hint: 'ojalá que → Subjuntivo\nhacer → haga' },
    ],
  },

  /* ── 12. Imperativo negativo ── */
  {
    id: 11, name: 'Imperativo negativo', tag: 'Императив',
    rule: 'Отрицательные команды = формы Presente de Subjuntivo:\n\nNo hables (tú) = No hagas, no vayas, no seas, no digas\nNo habléis (vosotros) = No hagáis, no vayáis, no seáis\nNo hable (usted) = No haga, no vaya, no sea\n\nАфирм. imperativo (habla, haz, ve) ≠ Subj\nОтриц. imperativo (no hables, no hagas) = Subj',
    examples: [
      'No seas tan serio. (≠ No eres tan serio)',
      'No hagas ruido, por favor.',
      'No vayas sin abrigo.',
      'No les digas nada.',
    ],
    questions: [
      { question: 'Por favor, no ___ tan tarde. Necesitamos salir.  (llegar, tú)',
        options: ['llegues', 'llegas', 'llega', 'llegaste'], correct: 0,
        hint: 'Imperativo negativo (tú) = Subjuntivo\nllegar + tú → llegues (g→gu)' },
      { type: 'fill', sentence: 'No ___ ese error otra vez.', sentenceRu: 'Не совершай эту ошибку снова.', verb: 'cometer (tú) — imperativo negativo',
        tiles: ['cometas', 'cometes', 'cometiste', 'cometerás'], correct: 0,
        hint: 'Imperativo negativo (tú) = Subjuntivo\ncometer + tú → cometas (-ER → -as)' },
      { question: 'No ___ ruido, que el bebé está durmiendo.  (hacer, vosotros)',
        options: ['hagáis', 'hacéis', 'hacíais', 'haréis'], correct: 0,
        hint: 'Imperativo negativo (vosotros) = Subjuntivo\nhacer: yo hago → hag- → vosotros hagáis' },
      { type: 'fill', sentence: 'No ___ de eso con nadie, es un secreto.', sentenceRu: 'Не говори об этом никому — это секрет.', verb: 'hablar (tú) — imperativo negativo',
        tiles: ['hables', 'hablas', 'habla', 'hablarás'], correct: 0,
        hint: 'Imperativo negativo (tú) = Subjuntivo\nhablar + tú → hables' },
      { question: 'No ___ sin llamar antes.  (venir, tú)',
        options: ['vengas', 'vienes', 'ven', 'vendrás'], correct: 0,
        hint: 'Imperativo negativo (tú) = Subjuntivo\nvenir: yo vengo → veng- → tú vengas' },
    ],
  },

];
